//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_sicge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRol
    {
        public string UserId { get; set; }
        public int RolId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual PersonUser PersonUser { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
